# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog For Andy's Life
tagline:          'A Jekyll theme'
description:      'Just Waiting...'
url:              https://github.com/GitHub4Andy
baseurl:          /

author:
  name:           'Andy Huang'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/GitHub4Andy
